### ISSUE TITLE
Need descriptions for Mirai and DDOS

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/refdata-risk#2]
Currently description fields for this two risks are empty. Looks ugly on website. 
Would be nice if we have them

### Task

- [x] Copy descriptions from Wikipedia
  - [Mirai](https://en.wikipedia.org/wiki/Mirai_(malware))
  - [DDOD](https://en.wikipedia.org/wiki/Denial-of-service_attack#Distributed_attack)
- [x] markdown properly
- [x] push to this repo
- [x] Integrate (load to DB)

**Comment by aaronkaplan** [comment]
> On 19 Jan 2017, at 10:26, Irakli Mchedlishvili <notifications@github.com> wrote:
> 
> Currently description fields for this two risks are empty. Looks ugly on website.
> Would be nice if we have them


https://en.wikipedia.org/wiki/Mirai_(malware)

**Comment by zelima** [comment]
FIXED see https://cybergreen-staging.herokuapp.com/risk/ddos and https://cybergreen-staging.herokuapp.com/risk/mirai
